### PR TITLE
define Client type

### PR DESCRIPTION
**Pull request by MikePodgorniy**
ApolloClient<NormalizedCache | NormalizedCacheObject>

### CODE REVIEW

**Comment by plrdev** [comment]
What is the `NormalizedCacheObject` in this one?

**Comment by MikePodgorniy** [comment]
the result type of apollo client with some InMemoryCache config

**Comment by MikePodgorniy** [comment]
And maybe you need to define types for logger cb function?  

```typescript 
    const logger = ({
      state: { queries, mutations },
      dataWithOptimisticResults: inspector,
    }: {
      state: {
        queries: any;
        mutations: any;
      };
      dataWithOptimisticResults: any;
    }) => {
      counter++;
      enqueued = {
        counter,
        queries,
        mutations,
        inspector,
      };
      if (currentConnection !== null) {
        currentConnection.send('broadcast:new', enqueued);
      }
    };
    client.__actionHookForDevTools(logger as () => void);
```

**Comment by plrdev** [comment]
> And maybe you need to define types for logger cb function?

Yeah all of this would benefit from typing properly, so go ahead if you are able to figure out the types!

**Review by plrdev — APPROVED** [review]

**Pull request merged**
